pool:
  vmImage: ubuntu-24.04
trigger:
  - main
stages:
  - stage: buildstage
   jobs:
    - job: buildjob
   steps:
     - task: Maven@4
       inputs:
         mavenPomFile: pom.xml
         goal: validate
         jdkVerionOption: '1.17'
       
